#This is the configuration for BungeeBan by VinciDev.
#The source for the plugin can be found at http://vincidev.de/vincidev/BungeeBan/tree/master
#Releases can be found at http://vincidev.de/vincidev/BungeeBan/tree/master/releases

#Wiki: http://vincidev.de/vincidev/BungeeBan/wikis/home

#ATTENTION: If you are coming from BungeeBan 2.5, Ban and Mute migration unfortunately isn't possible.

#Select your backend type here. Either put 'sqlite' for SQLite, or 'mysql' for MySQL
backend: 'sqlite'

#If you want to use SQLite, edit the path to the sqlite database if you want to (not needed)
sqlite:
  file: 'plugins/BungeeBan/data.db'

#Set your API location. Either 'eu' or 'us' is possible. Pick the one you live closer to for maximum speed. Currently, many users reported errors with the eu api,
#but if it works again you can use it.
api: 'us'

#If you want to use MySQL, enter your login data here. Make sure your user has access to the database
mysql:
  host: '127.0.0.1'
  port: 3306
  username: 'bungeeban'
  password: 'abc123'
  database: 'bungeeban'

#Players who are muted can't access these commands
mute_deny_commands:
- '/msg'
- '/tell'
  
#Edit the language configuration here. It should be self explanatory.
#
#Theese are the placeholders available: 
#(Of course not every placeholder is available everywhere. They are only available, where they make sense.)
#
#{NAME} - The name of the player
#{UUID} - The uuid of the player
#{REASON} - The reason for a players ban/mute/kick
#{REMAININGTIME} - The remaining time of the ban/mute, using the below specified timeformat
#{BY} - The name of the person who has banned/muted/kicked the player
#{DETAILS} - If a message has some details, use this. (Only useful for internal error message)
#
lang:

  prefix: '&8[&cBungeeBan&8] '
  console_prefix: '[BungeeBan] '
  time_format: '{DAYS} day(s), {HOURS} hour(s), {MINUTES} min(s) and {SECONDS} sec(s)'
  time_format_permanent: 'PERMANENT'
  
  errors:
    no_permissions: '&cYou are not allowed to use this.'
    cooldown: '&cPlease wait before using this again.'
    have_to_be_player: '&cYou have to be a player to use this.'
    player_uuid_not_found: '&cThe UUID of this player could not be found.'
    player_not_online: '&cThe player &e{NAME} &cis not online.'
    internal_error: '&cAn internal error occured: &e{DETAILS}'
    player_already_banned: '&cThe player &e{NAME} &cis already banned.'
    player_not_banned: '&cThe player &e{NAME} &cis not banned.'
    player_already_muted: '&cThe player &e{NAME} &cis already muted.'
    player_not_muted: '&cThe player &e{NAME} &cis not muted.'
    unknown_timeunit: '&cUnknown timunit. <sec|min|h|days>'

  banmessage:
  - '&cYou have been banned from the server!'
  - '&cReason: &e{REASON}'
  - '&cBanned By: &e{BY}'
  - '&cRemaining time: &e{REMAININGTIME}'

  mutemessage:
  - '&cYou are currently muted.'
  - '&cReason: &e{REASON}'
  - '&cBanned By: &e{BY}'
  - '&cRemaining time: &e{REMAININGTIME}'

  kickedmessage:
  - '&cYou have been kicked from the server!'
  - '&cReason: &e{REASON}'
  - '&cKicked By: &e{BY}'

  commands:
    ban:
      syntax: '&3Usage: &e/ban <Player> <Reason>'
      banned: '&aYou have successfully banned &e{NAME}&a.'
      broadcast:
      - '&e{NAME} &chas been banned by &e{BY}&c.'
      - '&cReason: &e{REASON}'
      - '&cTime: &e{REMAININGTIME}'
    tempban:
      syntax: '&3Usage: &e/tempban <Player> <Time> <TimeUnit> <Reason>'
      banned: '&aYou have successfully banned &e{NAME}&a.'
      broadcast:
      - '&e{NAME} &chas been banned by &e{BY}&c.'
      - '&cReason: &e{REASON}'
      - '&cTime: &e{REMAININGTIME}'
    unban:
      syntax: '&3Usage: &e/unban <Player>'
      unbanned: '&aYou have successfully unbanned &e{NAME}&a.'
      broadcast:
      - '&e{NAME} &chas been unbanned by &e{BY}&c.'
    mute:
      syntax: '&3Usage: &e/mute <Player> <Reason>'
      muted: '&aYou have successfully muted &e{NAME}&a.'
      broadcast:
      - '&e{NAME} &chas been muted by &e{BY}&c.'
      - '&cReason: &e{REASON}'
      - '&cTime: &e{REMAININGTIME}'
    tempmute:
      syntax: '&3Usage: &e/tempmute <Player> <Time> <TimeUnit> <Reason>'
      muted: '&aYou have successfully muted &e{NAME}&a.'
      broadcast:
      - '&e{NAME} &chas been muted by &e{BY}&c.'
      - '&cReason: &e{REASON}'
      - '&cTime: &e{REMAININGTIME}'
    unmute:
      syntax: '&3Usage: &e/unmute <Player>'
      unmuted: '&aYou have successfully unmuted &e{NAME}&a.'
      broadcast:
      - '&e{NAME} &chas been unmuted by &e{BY}&c.'
    kick:
      syntax: '&3Usage: &e/kick <Player> <Reason>'
      kicked: '&aYou have successfully kicked &e{NAME}&a.'
      broadcast:
      - '&e{NAME} &chas been kicked by &e{BY}&c.'
      - '&cReason: &e{REASON}'
    check:
      syntax: '&3Usage: &e/check <Player>'
      banned:
        positive:
        - '&3The player &e{NAME} &4is banned&3.'
        - '&3Reason: &e{REASON}'
        - '&3By: &e{BY}'
        - '&3Remaining time: &e{REMAININGTIME}'
        negative:
        - '&3The player &e{NAME} is &2not banned&3.'
      muted:
        positive:
        - '&3The player &e{NAME} &4is muted&3.'
        - '&3Reason: &e{REASON}'
        - '&3By: &e{BY}'
        - '&3Remaining time: &e{REMAININGTIME}'
        negative:
        - '&3The player &e{NAME} is &2not muted&3.'
      uuid: '&3UUID: &e{UUID}'